### ISSUE TITLE
Support for python3.8

### ISSUE THREAD

**Issue by stefanik12** [nlgranger/SeqTools#6]
Hey, I bumped into an issue rather quickly :)
On python==3.8.12, I ran:
```shell
pip install seqtools
python
```
```python
import seqtools
```
and am getting:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/__init__.py", line 23, in <module>
    from .evaluation import prefetch
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 41, in <module>
    class ProcessBacked(AsyncWorker):
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 110, in ProcessBacked
    def cleanup(job_queue, workers: list[multiprocessing.Process], monitor):
TypeError: 'type' object is not subscriptable
```
so I checked the supported versions of python on [pypi](https://pypi.org/project/SeqTools), and found `Requires: Python >=3.8`. 

Do you think it could be possible to still support python==3.8, e.g. by adding `from __future__ import annotations`?

Thanks!

**Comment by nlgranger** [comment]
Can you test the latest release and let me know if it works?

**Comment by stefanik12** [comment]
@nlgranger I've updated the library to `seqtools==1.4.1`, and I no longer encounter any issues related to the python version. Closing the issue.

Thanks!
