### ISSUE TITLE
Prefetch fails with generator and `nworkers>0`

### ISSUE THREAD

**Issue by stefanik12** [nlgranger/SeqTools#7]
I am trying to use `prefetch` with generators and after reading through its [docs](https://seqtools-doc.readthedocs.io/en/stable/reference.html#seqtools.prefetch) and [examples](https://seqtools-doc.readthedocs.io/en/stable/examples.html), I still can not find any configuration where it would work for me. What I am trying to achieve is to have an asynchronous buffer on a generator that will fetch the next sample in parallel to the main thread.

In the following snippet of code, I found that with the default `nworkers=0`, `prefetch` does nothing, i.e. it just [returns the input sequence](https://github.com/nlgranger/SeqTools/blob/f9d06f738481ed94ab3b62a0e913503cc2231fba/seqtools/evaluation.py#L462-L463), which surprised me, as prefetching would also make sense with a single parallel thread. As a result, the time of fetching either sample does not decrease (which is what I am trying to achieve):

```python
import time
import seqtools

def wait_and_return(i):
    time.sleep(1)
    return i ** 2

output_generator = (wait_and_return(i) for i in range(10))

output_generator = seqtools.prefetch(output_generator, max_buffered=10, nworkers=0)
output_generator_iter = iter(output_generator)

# fetching first sample
start_time = time.time()
print(next(output_generator_iter))
# >>> 0
end_time = time.time()
print("Time of fetching first sample: %s sec" % (end_time - start_time))  # expected: around 1 sec
# >>> Time of fetching first sample: 1.0063753128051758 sec

# waiting for prefetch
time.sleep(2)

# fetching second sample
start_time = time.time()
print(next(output_generator_iter))
# >>> 1
end_time = time.time()
print("Time of fetching second sample: %s sec" % (end_time - start_time))  # expected: close to 0 sec
# >>> Time of fetching second sample: 1.006392002105713 sec
```

However, increasing the number of workers e.g. to `nworkers=2`, will raise an error:
```python
Traceback (most recent call last):
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 329, in worker
    value = seq[idx]
TypeError: 'generator' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 384, in __iter__
    yield self[i]
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 412, in __getitem__
    reraise_err(item, value, self.creation_stack)
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 358, in reraise_err
    raise EvaluationError(msg) from error
seqtools.errors.EvaluationError: failed to evaluate item 0 in prefetch created at :
  File "<stdin>", line 1, in <module>
  File "/Users/xstefan3/miniconda/envs/adaptor/lib/python3.8/site-packages/seqtools/evaluation.py", line 485, in prefetch
    return Prefetch(size, backend, buffer_size=max_buffered, init_stack=format_stack())
```

I am wondering if this is an expected behavior? 

If so, is there a way to achieve asynchronous pre-fetching with a generator using `SeqTools`?

Thank you!

**Comment by nlgranger** [comment]
Seqtools does not handle iterables/iterators, only sequences, for that you can use Python's itertools and ThreadPoolExecutor stuff, seqtools provides smap and prefetch to do it on sequences.
Basically you need to modify your example like so:

```py
import time
import seqtools

def wait_and_return(i):
    time.sleep(1)
    return i ** 2

indices = list(range(10))
output_generator = seqtools.smap(wait_and_return, indices)

output_generator = seqtools.prefetch(output_generator, max_buffered=10, nworkers=1)
output_generator_iter = iter(output_generator)

# fetching first sample
start_time = time.time()
print(next(output_generator_iter))
# >>> 0
end_time = time.time()
print("Time of fetching first sample: %s sec" % (end_time - start_time))  # expected: around 1 sec
# >>> Time of fetching first sample: 1.0063753128051758 sec

# waiting for prefetch
time.sleep(2)

# fetching second sample
start_time = time.time()
print(next(output_generator_iter))
# >>> 1
end_time = time.time()
print("Time of fetching second sample: %s sec" % (end_time - start_time))  # expected: close to 0 sec
# >>> Time of fetching second sample: 0.0001647472381591797 sec
```

EDIT: I'd like to emphasize that smap is lazy, it's computation-free until you actually start getting items from it.

**Comment by stefanik12** [comment]
Thank you @nlgranger for clarification!
